version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12

  pre_build:
    commands:
      # install dependencies
      - echo installing dependencies...
      - npm install

  build:
    commands:
      # run build script
      - echo Build started on `date`
      - echo Building React Application...
      - npm run build
  
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  # include all files required to run application
  # we include only the static build files
  files:
    - "**/*"
   # reference directory where build file is located
  base-directory: "build"